name: pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write
      actions: read

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - uses: actions/setup-node@v4
        with:
          cache: "npm"

      - run: npm ci

      - name: Build website
        run: npx eleventy # --pathprefix=/gruber/
        env:
          NODE_ENV: production

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: bundle/website

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
